apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: chai-app
  namespace: argocd

  annotations:
    # Docker image to track
    argocd-image-updater.argoproj.io/image-list: chai-app=sujaldedaniya1014/blue-green

    # Git write-back method
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds

    # Use semantic versioning strategy
    argocd-image-updater.argoproj.io/chai-app.update-strategy: semver

    # Allow only semantic version tags like v1.0.0
    argocd-image-updater.argoproj.io/chai-app.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$

    # Force image updates even if ArgoCD thinks nothing changed
    argocd-image-updater.argoproj.io/chai-app.force-update: "true"

spec:
  project: default

  source:
    repoURL: https://github.com/Sujal-Dedaniya/blue-green-app.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
